---
base_security_ingress_rules:
  - proto: tcp
    from_port: 22
    to_port: 22
    #cidr_ip: 162.208.41.38/24 #MOP
    cidr_ip: 0.0.0.0/0 # don't add SecurityGroup whitelist for ssh ( need private key )
  - proto: tcp
    from_port: 80
    to_port: 80
    cidr_ip: 0.0.0.0/0
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: 0.0.0.0/0

base_security_egress_rules:
  - proto: all
    from_port: 0
    to_port: 65535
    cidr_ip: 0.0.0.0/0

aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
